obrazkiwbazie:
    resource: "@ObrazkiwbazieBundle/Controller/"
    type:     annotation
    prefix:   /
# _zbior:
#    pattern: /zbior
#    defaults: { _controller: ObrazkiwbazieBundle:wrap:Blank _defaults


