obrazkipf:
    resource: "@ObrazkipfBundle/Controller/"
    type:     annotation
    prefix:   /

glowna_plakaty:
    resource: "@glownaPlakatyBundle/Controller/"
    type:     annotation
    prefix:   /

obrazkijako_produkty:
    resource: "@ObrazkijakoProduktyBundle/Controller/"
    type:     annotation
    prefix:   /

obrazkiwbazie:
    resource: "@ObrazkiwbazieBundle/Controller/"
    type:     annotation
    prefix:   /



# _zbior:
#    pattern: /zbior
#    defaults: { _controller: ObrazkiwbazieBundle:wrap:Blank _defaults

kategoirie:
    pattern: /index
    defaults: {_controller:ObrazkiwbazieBundle:ObrazkiwKategorii:index }
#
#panel:
#     path:   /wszystkieZamowienia
#     defaults:  { _controller: glownaPlakatyBundle:panel:wszystkieZamowienia }